Fix mesop web_component to make it work in Windows
airtai/fastagency pull request #415
Opened 2024-10-16 12:11 UTC by kumaranvpl

# Description

`MesopUI` is not working in `Windows` with weird error. Flask was complaining that `wakeup_component.js`. After a short conversation with @davorinrusevljan, I have learnt about the patching we do for mesop. This patching is not working in `Windows`.

I have investigated further and discovered a bug in `mesop.labs.web_component` - https://github.com/google/mesop/blob/main/mesop/labs/web_component.py#L34-L35. Here a `/` is prepended to a path but this piece of code forgets the fact that the windows uses `\` instead of `/`.

I have fixed it by introducing a patched function and using that patched function. Ideally this bug fix should be made at mesop repo itself but I don't want to wait till they make the fix as we have some potential Windows users.

Fixes #413

## Type of change

- [ ] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have conducted a self-review of my own code
- [ ] I have made the necessary changes to the documentation
- [ ] My changes do not generate any new warnings
- [ ] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] I have included code examples to illustrate the modifications

2024-10-16 13:23 UTC, davorrunje approved these changes

2024-10-16 13:28 UTC, davorrunje requested changes
Let me check something first

2024-10-17 13:55 UTC, davorinrusevljan reviewed
Looks good to me.

2024-10-17 13:55 UTC, davorinrusevljan commented on fastagency/ui/mesop/timer.py
> +def patch_os_and_str() -> Iterator[None]:
Do we have to worry if 2 threads attempt to execute this at the same time? In that case the one that finishes first would possibly remove patch for the second one at too early stage. 

But I am not sure if we could have 2 threads hitting this code at the same time.

2024-10-18 07:06 UTC, davorrunje approved these changes

2024-10-18 07:12 UTC, merged